"""EventEnrichers""" = [
    {
        """Name""" = """UCE-tag-embargoed-country"""
        """DisplayName""" = """Tag Embargoed Country"""
        """Condition""" = """(InList(geo_src_ip.country, 'af', 'by', 'cd', 'cf', 'cu', 'et', 'iq', 'ir', 'kp', 'lb', 'ly', 'mm', 'ni', 'ru', 'sd', 'ss', 'sy', 've', 'xk', 'ye', 'zw') OR InList(geo_dest_ip.country, 'af', 'by', 'cd', 'cf', 'cu', 'et', 'iq', 'ir', 'kp', 'lb', 'ly', 'mm', 'ni', 'ru', 'sd', 'ss', 'sy', 've', 'xk', 'ye', 'zw'))"""
        """Map""" = [
            {
                """Field""" = """tag"""
                """Value""" = """trim('Embargoed Country')"""
            }
        ]
	}
]
