"""EventEnrichers""" = [
    {
        """Name""" = """crowdstrike-user-custom-1"""
        """DisplayName""" = """CrowdStrike asset ID to User Lookup - Custom - 1"""
        """Description""" = """CrowdStrike user by aid - Custom - 1"""
        """Condition""" = """exists(aid) && HasContextKey('CrowdStrike Users', aid) && !exists(user)"""
        """Map""" = [
            {
                """Field""" = """user"""
                """Value""" = """GetContextAttribute('CrowdStrike Users', aid, '4Tqx7Km1UB')"""
            },
	    {
                """Field""" = """user_sid"""
                """Value""" = """"""
            }
        ]
        """Filter""" = {
            """UniversalFieldName""" = """vendor"""
            """UniversalFieldValues""" = [
                """CrowdStrike"""
            ]
        }
    }
]